# Generated by Django 6.0 on 2025-12-07 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Укажите название курса",
                        max_length=100,
                        verbose_name="Название курса",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        help_text="Добавьте заставку для курса",
                        upload_to="courses/image",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Добавьте описание",
                        null=True,
                        verbose_name="описание курса",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название урока",
                        max_length=100,
                        verbose_name="Название урока",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Добавьте описание",
                        null=True,
                        verbose_name="описание урока",
                    ),
                ),
                (
                    "preview",
                    models.ImageField(
                        blank=True,
                        help_text="Добавьте заставку для урока",
                        null=True,
                        upload_to="",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True,
                        help_text="укажите ссылку на урок",
                        null=True,
                        verbose_name="ссылка на урок",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        help_text="Выберите, к какому курсу относится урок",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lms.course",
                        verbose_name="Название курса",
                    ),
                ),
            ],
        ),
    ]
