# Generated by Django 6.0 on 2025-12-07 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True,
                help_text="Добавьте заставку для курса",
                null=True,
                upload_to="courses/image",
            ),
        ),
    ]
